version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

#  elasticsearch:
#    image: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
